[phases.setup]
nixPkgs = ['nodejs_20']

[phases.install]
cmds = ['rm -f package-lock.json', 'npm install --legacy-peer-deps --no-package-lock']

[phases.build]
cmds = ['echo "No build step required"']

[start]
cmd = 'node src/index.js'
